export const GET_WORDS = "GET_WORDS";
export const GET_WORDS_SUCCESS = "GET_WORDS_SUCCESS";
export const GET_WORDS_FAIL = "GET_WORDS_FAIL";

export const ADD_WORD = "ADD_WORD";
export const ADD_WORD_SUCCESS = "ADD_WORD_SUCCESS";
export const ADD_WORD_FAIL = "ADD_WORD_FAIL";

export const DELETE_WORD = 'DELETE_WORD';
export const DELETE_WORD_SUCCESS = 'DELETE_WORD_SUCCESS';
export const DELETE_WORD_FAIL = 'DELETE_WORD_FAIL';

export const UPDATE_WORD = 'UPDATE_WORD';
export const UPDATE_WORD_SUCCESS = 'UPDATE_WORD_SUCCESS';
export const UPDATE_WORD_FAIL = 'UPDATE_WORD_FAIL';

export const CREATE_REPETITION_SET = 'CREATE_REPETITION_SET';
export const CREATE_REPETITION_SET_SUCCESS = 'CREATE_REPETITION_SET_SUCCESS';
export const CREATE_REPETITION_SET_FAIL = 'CREATE_REPETITION_SET_FAIL';

export const SELECT_OPTION = 'SELECT_OPTION';

export const COMPLETE_REPETITION = 'COMPLETE_REPETITION';
export const COMPLETE_REPETITION_SUCCESS = 'COMPLETE_REPETITION_SUCCESS';
export const COMPLETE_REPETITION_FAIL = 'COMPLETE_REPETITION_FAIL';